spring:
  application:
    name: Loan Calculator

  mvc:
   view:
     prefix: /WEB-INF/jsp/
     suffix: .jsp
  datasource:
    url: jdbc:h2:mem:loanCal
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
  h2:
    console:
      enabled: true
      path: /h2-console

